---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: code-server
  name: code-server
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - name: code-server
    image: cdecelles/code-server:latest
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: "/home/coder/project"
      name: code-server-project-data
  volumes:
    - name: code-server-project-data
      persistentVolumeClaim:
        claimName: pvc-code-server
